"""Centralized constants for the Route Explorer codebase."""

# --- AKAZE / Feature Matching ---
AKAZE_DISTANCE_THRESHOLD = 80
TOP_K_CANDIDATES = 20
TOP_K_COARSE = 20
TOP_K_OUTPUT_JSON = 5
MIN_MATCHES_FOR_HOMOGRAPHY = 6
RANSAC_REPROJECTION_THRESHOLD = 5.0
MIN_HOMOGRAPHY_INLIERS = 5
OFF_PATCH_INLIER_PENALTY = 0.5
DEBUG_DRAW_MATCHES_LIMIT = 40
MAX_WORKERS_PRECOMPUTE = 4

# --- Localization ---
CONFIDENCE_THRESHOLD = 0.12
MIN_EXPECTED_MATCHES = 40.0
LOST_FRAMES_BEFORE_GLOBAL = 6
LOST_FRAMES_BEFORE_EXPANDING = 5
TELEPORT_DISTANCE_PX = 1500
CACHE_CAPACITY = 50

# --- Multi-scale ---
DEFAULT_SCALES = (0.9, 1.0, 1.1)

# --- Viterbi Optimizer ---
LOST_EMISSION_COST = 2.0
LOST_TRANSITION_PENALTY = 1.0
MAX_SPEED_TILES_PER_SEC = 1.5
TRANSITION_SPEED_MULTIPLIER = 0.2
TELEPORT_TRANSITION_COST = 0.5
OVER_SPEED_BASE_PENALTY = 20.0
OVER_SPEED_VELOCITY_MULTIPLIER = 5.0

# --- OCR ---
OCR_DOWNSCALE_FACTOR = 0.5
INVALID_PUZZLE_NUMBER = -1

# --- Tile ---
DEFAULT_TILE_SIZE = 256

# --- Extraction / Verification ---
DEFAULT_VERIFICATION_FRAMES = 8
DEFAULT_VERIFICATION_COLS = 4
THUMB_WIDTH = 320
THUMB_HEIGHT = 180
SHEET_PADDING = 5
LABEL_HEIGHT = 25
SHEET_BG_COLOR = (40, 40, 40)
JPEG_QUALITY = 90
VERIFY_WINDOW_SIZE = (1280, 720)
DEFAULT_EXTRACTION_FPS = 1

# --- Filmstrip ---
FILMSTRIP_INTERVAL_SECONDS = 30
FILMSTRIP_THUMB_SIZE = 128
FILMSTRIP_PADDING = 10
FILMSTRIP_LABEL_HEIGHT = 30
FILMSTRIP_EXTRA_WIDTH = 200
FILMSTRIP_BG_COLOR = (30, 30, 30)
FILMSTRIP_CIRCLE_THICKNESS = 2
FILMSTRIP_FONT_SCALE = 0.7

# --- HTTP Cache ---
HTTP_CACHE_MAX_AGE_TILES = 604800  # 7 days
HTTP_CACHE_MAX_AGE_MEDIA = 86400  # 1 day
DEFAULT_SERVER_PORT = 9090

# --- Circular Mask ---
CIRCULAR_MASK_RADIUS_SCALE = 0.90

# --- Benchmark ---
CONFIDENCE_HISTOGRAM_BINS = 10
HISTOGRAM_BIN_SCALE = 10.0
